<div class="box">
    <div class="box_title">全部文章</div>
    <div class="box_body">
        <div class="article">
            <a href="#" class="a">
                <h1 class="title">HTML5 发展历史</h1>
                <div class="content">HTML 5草案的前身名为Web Applications 1.0，是在2004年由WHATWG提出。2008年1月22日，第一份正式草案发布。WHATWG表示该规范是目前仍在进行的工作，仍须多年的努力。[8]目前Mozilla Firefox、Google Chrome、Opera、Safari（版本4以上）、Internet Explorer（版本9以上）已支持HTML5技术。</div>
                <div class="state">2013-11-11 16:14:37</div>
            </a>
        </div>
    </div>
</div>


<div class="pager">
    <a href="#" class="first item">首页</a>
    <a href="#" class="prev item">上一页</a>
    <div class="cur item">1</div>
    <a href="#" class="next item">下一页</a>
    <a href="#" class="last item">尾页</a>
</div>
