<div class="articleList-box">
    <?php /**
     * @var \app\libraries\Page $page
     */
    if ($page->getTotalItems() > 0) {?>
        <div class="box">
            <div class="box_title">最新文章</div>
            <div class="box_body">
                <?php
                foreach ($page->getItems() as $item) {
                    ?>
                    <div class="article">
                        <div class="head">
                            <h1 class="title"><a href="/index/article-<?php echo rawurlencode($item['encrypt_id'])?>.html"><?php echo $item['title']?></a></h1>
                            <ul class="show">
                                <li class="item">评论数</li>
                                <li class="item">阅读数</li>
                            </ul>
                            <div class="clear"></div>
                        </div>
                        <div class="content"><?php echo (new \Phalcon\Filter())->sanitize($item['content'], 'striptags');?></div>
                        <div class="state"><?php echo $item['ctime']?></div>
                    </div>
                    <?php
                }
                ?>
            </div>
        </div>


        <div class="pager">
            <a href="/index/list.html" class="first item">首页</a>
            <a href="/index/list-<?php echo $page->getBefore()?>.html" class="prev item">上一页</a>
            <div class="cur item"><?php echo $page->getCurrent()?>/<?php echo $page->getTotalPages()?></div>
            <a href="/index/list-<?php echo $page->getNext()?>.html" class="next item">下一页</a>
            <a href="/index/list-<?php echo $page->getTotalPages()?>.html" class="last item">尾页</a>
        </div>
    <?php }else {?>
        <div class="nobody">没有任何文章</div>
    <?php }?>
</div>