<div class="articleList-box">
    <?php if ($this->flashSession->has('error')) { ?>
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            <?php
            foreach ($this->flashSession->getMessages('error') as $message) {
                echo "<p>{$message}</p>";
            }
            ?>
        </div>
    <?php } ?>

    <?php /**
     * @var \app\libraries\Page $page
     */
    if ($page->getTotalItems() > 0) {?>
    <div class="box">
        <div class="box_title">我的文章</div>
        <div class="box_body">
            <?php
                foreach ($page->getItems() as $item) {
                    ?>
                    <div class="article">
                        <div class="head">
                            <h1 class="title"><a href="/user/article-<?php echo rawurlencode($item['encrypt_id'])?>.html"><?php echo $item['title']?></a></h1>
                            <ul class="opt">
                                <?php if($item['status']==1){?>
                                    <li><a class="item" href="/user/public-<?php echo $item['id']?>-<?php echo $page->getCurrent()?>.html">发布</a></li>
                                <?php }?>
                                <li><a class="item" href="/user/update-<?php echo $item['id']?>-<?php echo $page->getCurrent()?>.html">修改</a></li>
                                <li><a class="item" href="/user/del-<?php echo $item['id']?>-<?php echo $page->getCurrent()?>.html">删除</a></li>
                            </ul>
                            <ul class="show">
                                <li class="item"><?php echo $item['status']==1 ? '未发布' : '已发布'?></li>
                                <li class="item">评论数</li>
                                <li class="item">阅读数</li>
                            </ul>
                            <div class="clear"></div>
                        </div>
                        <div class="content"><?php echo $item['short_content']?></div>
                        <div class="state"><?php echo $item['ctime']?></div>
                    </div>
                    <?php
                }

            ?>
        </div>
    </div>


    <div class="pager">
        <a href="/user/<?php echo $drag ? 'drag' : 'list'?>.html" class="first item">首页</a>
        <a href="/user/<?php echo $drag ? 'drag' : 'list'?>-<?php echo $page->getBefore()?>.html" class="prev item">上一页</a>
        <div class="cur item"><?php echo $page->getCurrent()?>/<?php echo $page->getTotalPages()?></div>
        <a href="/user/<?php echo $drag ? 'drag' : 'list'?>-<?php echo $page->getNext()?>.html" class="next item">下一页</a>
        <a href="/user/<?php echo $drag ? 'drag' : 'list'?>-<?php echo $page->getTotalPages()?>.html" class="last item">尾页</a>
    </div>
    <?php }else {?>
    <div class="nobody">没有任何文章</div>
    <?php }?>
</div>