<div class="login-box">
    <div class="login-title"><h1>用户登录</h1></div>
    <?php
    if ($this->flashSession->has('error')) {
        $messages = $this->flashSession->getMessages('error');
        foreach ($messages as $message) {
            echo '<div class="alert alert-danger alert-dismissible errors" role="alert">';
            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>';
            echo $message;
            echo '</div>';
        }
    }
    ?>

    <div class="login-body">
        <form action="/user/login" method="post">
            <input type="hidden" name="form" value="login"/>
            <div class="login-item"><input class="input-text" type="text" name="account" placeholder="手机号或邮箱"/></div>
            <div class="login-item"><input class="input-text" type="password" name="password" placeholder="密码"></div>
            <div class="login-item login-item2">
                <label>
                    <input class="input-checkbox" type="checkbox" value="1" name="rememberMe" checked>
                    <span>保持登录</span>
                </label>
                <a href="#" class="forget">忘记密码？</a>
            </div>
            <div class="login-item">
                <button class="submit" type="submit">立即登录</button>
            </div>
        </form>
    </div>
</div>