<div class="toWrite-box">
    <div style="display: none" id="hiddenDom"></div>
    <form class="form-horizontal" id="mForm" action="/user/writeArticle" method="post">
        <input type="hidden" name="form" value="article"/>
        <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>' value='<?php echo $this->security->getToken() ?>'/>
        <input type="hidden" name="id" value="<?php echo !empty($article) ? $article['id'] : '' ?>"/>
        <input type="hidden" name="p" value="<?php echo !empty($p) ? $p : 1?>"/>
        <div class="form-group">
            <label for="title" class="col-md-1 control-label">标题</label>
            <div class="col-md-11">
                <input type="text" value="<?php echo !empty($article) ? $article['title'] : '' ?>" class="form-control"
                       name="title" id="title" placeholder="标题">
            </div>
        </div>
        <div class="form-group">
            <label for="content" class="col-md-1 control-label">内容</label>
            <div class="col-md-11">
                <textarea class="form-control" name="content" id="content"></textarea>
            </div>
        </div>
        <div class="form-group">
            <label for="content" class="col-md-1 control-label">标签</label>
            <div class="col-md-9">
                <input id="tags" name="tags"
                       value="<?php echo !empty($article) && !empty($article['tags']) ? implode(',', $article['tags']) : '' ?>"
                       placeholder="标签" class="form-control"/>
            </div>
            <div class="col-md-2">
                <button type="button" class="btn btn-info form-control" data-toggle="modal" data-target="#tag-pannel">
                    标签库
                </button>
            </div>
        </div>
        <input type="hidden" value="1" name="drag" id="drag"/>
        <div class="form-group">
            <div class="col-sm-offset-1 col-md-11">
                <button type="button" onclick="saveForm(2)" class="btn btn-success">提交</button>
                <button type="button" onclick="saveForm(1)" class="btn btn-primary">保存草稿</button>
            </div>
        </div>
    </form>

    <div class="modal fade" id="tag-pannel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">我的标签</h4>
                </div>
                <div class="modal-body">
                    <?php
                    /**
                     * @var \app\services\UserService $userService
                     */
                    $user = $this->di->get('userService')->getLoginedUser();
                    foreach ($user['tags'] as $tag) {
                        echo $tag['html'];
                    } ?>
                </div>
                <div class="modal-footer">
                    <button onclick="selectTags()" type="button" class="btn btn-primary" data-dismiss="modal">选择
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
$this->assets->addJs('/assets/plugs/ckeditor/ckeditor.js');
$this->assets->addInlineJs(<<<CODE
function saveForm(val) {
    var title = document.getElementById('title');
    var content = document.getElementById("content");
    var drag = document.getElementById('drag');
    drag.value = val;

    if (title.value === "") {
        alert("标题不能为空");
    }

    var data = CKEDITOR.instances.content.getData();
    if (data === "") {
        alert("内容不能为空");
    }
    
    $("#hiddenDom").html(data);
    var codes=$("#hiddenDom pre code");
    if(codes.length){
        for(var i=0;i<codes.length;i++){
            var iHtml='';
            ss=$(codes[i]).html().split(/[\\n\\r]+/);
            iHtml+="<ul>";
            for(var k=0;k<ss.length;k++){
                iHtml+="<li class=\"cItem\">"+ss[k]+"</li>";
            }
            iHtml+="</ul>";
            $(codes[i]).html(iHtml);
            $(codes[i]).addClass("m_code");
        }
    }
    CKEDITOR.instances.content.setData($("#hiddenDom").html());
    

    /*console.log(data);*/
    $("#mForm").submit();
}


/**
 * 选择标签库标签
 */
function selectTags() {
    let tags = [];
    var tagChecks = $("#tag-pannel .modal-body .tag input");
    for (let i = 0; i < tagChecks.length; i++) {
        if (tagChecks[i].checked) {
            tags.push(tagChecks[i].value);
        }
    }
    document.getElementById("tags").value = tags.join(',');
}
CODE
);
$this->assets->addInlineJs('
CKEDITOR.replace("content", {
height: 600,
removePlugins:"cloudservices,easyimage",
});
CKEDITOR.editorConfig = function (config) {
    config.removePlugins = "easyimage,cloudservices";
};
var data=`'.(!empty($article) ? $article['content'] : '').'`;
$("#hiddenDom").html(data);
var codes=$("#hiddenDom pre code");
for(var p=0;p<codes.length;p++){
    var iHtml="";
    var tt=$(codes[p]).find("ul li.cItem");
    console.log(tt);
    for(var q=0;q<tt.length;q++){
        iHtml+=($(tt[q]).html()+"\n");
    }
    $(codes[p]).html(iHtml);
}
data = $("#hiddenDom").html();
CKEDITOR.instances.content.setData(data);
var tagChecks = $("#tag-pannel .modal-body .tag input");
var tagNames = `'.(!empty($article) && !empty($article["tags"]) ? implode(",", $article["tags"]) : "").'`.split(",");
if (tagNames.length>0) {
    for (var i = 0; i < tagChecks.length; i++) {
        for (var j = 0; j < tagNames.length; j++) {
            if (tagChecks[i].value === tagNames[j]) {
                tagChecks[i].checked = true;
            }
        }
    }
}
');

?>