<div class="showArticle-box panel panel-default">
    <div class="article panel-body">
        <h1 class="title"><?php echo $article['title']?></h1>
        <div class="meta">
            <div class="item date"><?php echo $article['ctime']?></div>
            <div class="item author"><span class="glyphicon glyphicon-user"></span><?php echo $article['nickname']?></div>
            <div class="item watch"><span class="glyphicon glyphicon-eye-open"></span><?php echo $article['look_num']?></div>
            <div class="item remark"><span class="glyphicon glyphicon-star-empty"></span><span class="val"><?php echo $article['star']?></span></div>
        </div>
        <div class="tag">标签：<span class="glyphicon glyphicon-tags"></span>
            <?php
                foreach ($article['tags'] as $tag){
                    echo '<a href="/blog/'.$tag['id'].'/list.html">'.$tag['name'].'</a>';
                }
            ?>
        </div>
        <div class="content"><?php echo $article['content']?></div>

        <div class="options">
            <div class="item star">
                <button onclick="star(<?php echo !empty($user) ? $user['id'] : 0?>,'<?php echo $article['encrypt_id']?>');" class="btn btn-primary" type="button"><span class="glyphicon glyphicon-thumbs-up"></span> 点赞</button>
                <div class="tip"></div>
            </div>

            <div class="clear"></div>
        </div>
    </div>
</div>

<div class="panel panel-default comment-box">
    <div class="panel-body">
        <div style="display: none" id="hiddenDom"></div>
        <div class="title">相关评论(<?php echo !empty($page) ? $page->getTotalItems() : 0?>)</div>
        <div class="form">
            <form id="mFrom" class="form" action="/blog/add-comment.html" method="post">
                <input type="hidden" name="form" value="comment"/>
                <input type='hidden' id="token" name='<?php echo $this->security->getTokenKey() ?>' value='<?php echo $this->security->getToken() ?>'/>
                <input type="hidden" id="articleId" name="articleId" value="<?php echo !empty($article) ? $article['id'] : '0' ?>"/>
                <input type="hidden" id="userId" name="userId" value="<?php echo !empty($user) ? $user['id'] : '0' ?>"/>
                <div class="form-group">
                    <textarea id="content" name="content" class="form-control content"></textarea>
                </div>
                <div class="form-group">
                    <button onclick="submitForm();" type="button" <?php echo empty($user) ? 'disabled' : ''?> class="btn btn-success">提交</button>
                    <p><?php echo empty($user) ? '登录后发表评论' : ''?></p>
                </div>
            </form>
        </div>
        <div class="comment-list" id="comment-list">
            <?php
            /**
             * @var \app\libraries\Page $page
             */
            if ($page !== false && $page->getTotalItems() > 0) { ?>
                <?php foreach ($page->getItems() as $comment) { ?>
                    <div class="comment">
                        <div class="left"><img src="<?php echo $comment['photo']?>"/></div>
                        <div class="right">
                            <div class="c_title"><?php echo $comment['nickname']?></div>
                            <div class="c_content">
                                <?php echo preg_replace("/@(.*?):/iu","<span class='ato'>@$1:</span>",$comment['content'])?>
                            </div>
                            <div class="reply"><span class="glyphicon glyphicon-share-alt"></span> <a href="javascript:void(0);" onclick="replyCemment('<?php echo $comment["nickname"]?>');">回复</a></div>
                        </div>
                    </div>
                <?php } ?>
            <?php } ?>
        </div>

        <div class="pager">
            <a onclick="getComment(1,'<?php echo $article['encrypt_id']?>')" href="javascript:void(0);" href="" class="first item">首页</a>
            <a onclick="getComment(<?php echo $page->getBefore()?>,'<?php echo $article['encrypt_id']?>')" href="javascript:void(0);" href="" class="prev item">上一页</a>
            <div class="cur item"><?php echo $page->getCurrent()?>/<?php echo $page->getTotalPages()?></div>
            <a onclick="getComment(<?php echo $page->getNext()?>,'<?php echo $article['encrypt_id']?>')" href="javascript:void(0);" href="" class="next item">下一页</a>
            <a onclick="getComment(<?php echo $page->getTotalPages()?>,'<?php echo $article['encrypt_id']?>')" href="javascript:void(0);" href="" class="last item">尾页</a>
        </div>
    </div>
</div>



<?php $this->assets->addInlineJs("hljs.initHighlightingOnLoad();"); ?>
<?php $this->assets->addJs('/assets/plugs/ckeditor/ckeditor.js');?>
<?php
$this->assets->addInlineJs('
    CKEDITOR.replace("content", {
        removePlugins:"cloudservices,easyimage",
        toolbar : [
            { name: "basicstyles", items: [ "Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript" ] },
            { name: "paragraph", items: [ "NumberedList", "BulletedList"] },
            { name: "links", items: [ "Link"] },
            { name: "insert", items: [ "EasyImageUpload", "CodeSnippet", "Table"] }
        ]
    });
    
    
    function submitForm() {
        var content = CKEDITOR.instances.content.getData();
        if (content === "") {
            alert("内容不能为空");
        }

        $("#hiddenDom").html(content);
        var codes=$("#hiddenDom pre code");
        if(codes.length){
            for(var i=0;i<codes.length;i++){
                var iHtml=\'\';
                ss=$(codes[i]).html().split(/[\\n\\r]+/);
                iHtml+="<ul>";
                for(var k=0;k<ss.length;k++){
                    iHtml+="<li class=\"cItem\">"+ss[k]+"</li>";
                }
                iHtml+="</ul>";
                $(codes[i]).html(iHtml);
                $(codes[i]).addClass("m_code");
            }
        }
        
        content = $("#hiddenDom").html();

        var userId = document.getElementById("userId").value;
        var articleId = document.getElementById("articleId").value;
        var token = document.getElementById("token");

        var data = {
            "content":content,
            "userId":userId,
            "articleId":articleId,
            "form":"comment"
        };
        data[token.name]=token.value;

        $.ajax({
            url:"/blog/add-comment.html",
            data:data,
            dataType:"JSON",
            type:"POST",
            success:function (data) {
                console.log(data);
                if(data.error===0){
                    token.name=data.data.token.key;
                    token.value=data.data.token.value;
                    var comment = data.data.comment;
                    var html="";
                    html+="<div class=\"comment\">";
                    html+=`<div class="left"><img src="`+comment.photo+`"/></div>`;
                    html+="<div class=\"right\">";
                    html+="<div class=\"c_title\">"+comment.nickname+"</div>";
                    html+="<div class=\"c_content\">";
                    html+=comment.content;
                    html+="</div>"; 
                    html+=`<div class="reply"><span class="glyphicon glyphicon-share-alt"></span> <a href="javascript:void(0);" onclick="replyCemment(\"`+comment.nickname+`\");">回复</a></div>`;
                    html+="</div></div>";
                    $("#comment-list").prepend(html);
                }
            },
            error:function (e) {
                console.log(e);
            }
        });
    }
    
    function replyCemment($ato) {
        var data = CKEDITOR.instances.content.getData();
        console.log(data);
        data= "@"+$ato+":"+ data.trim();
        console.log(data);
        CKEDITOR.instances.content.setData(data);
    }
    
    function star($userId,$articleId) {
        if($userId==0){
            $(".star .tip").empty();
            $(".star .tip").append(`先<a href="/user/login.html">登录</a>`);
            return false;
        }
    
        $.ajax({
            url:"/blog/star",
            type:"GET",
            data:{"userId":$userId,"articleId":$articleId},
            dataType:"JSON",
            success:function (data) {
                if(data.error==0){
                    $(".star .tip").empty();
                    $(".star .tip").append("点赞成功");
                    var star = $(".showArticle-box .article .meta .remark .val").text();
                    $(".showArticle-box .article .meta .remark .val").text(parseInt(star)+1);
                }else{
                    $(".star .tip").empty();
                    $(".star .tip").append(data.msg);
                }
            },
            error:function (e) {
                console.log("点赞失败",e.responseText);
            }
        })
    }
    
    
    function getComment($p,$articleId) {
        $.ajax({
            url:"/blog/getCommentsArticle",
            type:"GET",
            data:{"p":$p,"articleId":$articleId},
            dataType:"JSON",
            success:function (data) {
                console.log(data);
                if(data.error===0){
                    var page = data.data.page;
                    if(page.totalItems>0){
                        var html="";
                        for (let i = 0; i <page.items.length; i++) {
                            let comment = page.items[i];
                            html+="<div class=\"comment\">";
                            html+=`<div class="left"><img src="`+comment.photo+`"/></div>`;
                            html+="<div class=\"right\">";
                            html+="<div class=\"c_title\">"+comment.nickname+"</div>";
                            html+="<div class=\"c_content\">";
                            html+=comment.content;
                            html+="</div>";
                            html+=`<div class="reply"><span class="glyphicon glyphicon-share-alt"></span> <a href="javascript:void(0);" onclick="replyCemment(\"`+comment.nickname+`\");">回复</a></div>`;
                            html+="</div></div>";
                        }
                        $("#comment-list").html(html);
                    }
                }
            },
            error:function (e) {
                console.log("获取失败",e.responseText);
            }
        });
    }
    
');
?>

<script>

</script>
