<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Phalcon PHP Framework</title>
    <link rel="stylesheet" type="text/css" href="/assets/base/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/css/base.css?v=1"/>
    <?php $this->assets->outputCss();?>
</head>
<body>
<div class="header">
    <div class="container">
        <div class="logo col-md-3">
            <div class="right"><a href="/">zyBlog</a></div>
        </div>

        <?php if ($user = $this->userService->getLoginedUser()) { ?>
            <div class="col-md-3 col-md-offset-6">
                <div class="user">

                    <div class="pic"><a href="/user/articleList"><img class="img-circle" src="<?php echo $user['photo'] ?>"/></a></div>

                    <div class="name"><?php echo $user['nickname'] ?></div>

                    <div class="opt">
                        <a href="/user/toWrite">创作</a>
                        <span class="ls"> | </span>
                        <a href="/user/logout">退出</a>
                    </div>
                </div>
            </div>
        <?php } else { ?>
            <div class="col-md-2 col-md-offset-7 user-login">
                <a href="/user/loginHtml">登录</a>
                <a href="/user/registerHtml">注册</a>
            </div>
        <?php } ?>
    </div>
</div>


<div class="container">
    <?php echo $this->getContent(); ?>
</div>

<script src="/assets/base/js/jquery-3.3.1.slim.min.js"></script>
<script src="/assets/base/js/bootstrap.min.js"></script>
<script src="/assets/base/js/common.js"></script>
<?php
$this->assets->outputJs();
$this->assets->outputInlineJs();
?>

</body>
</html>
