<div class="row body">
    <?php
        $controller=$this->dispatcher->getControllerName();
        $viewStr='layouts/'.$controller;
        if($this->view->exists($viewStr)){
    ?>
        <div class="left"><?php echo $this->getContent();?></div>
        <div class="right">
            <?php
                $params=$this->view->getParamsToView();
                $this->view->partial('layouts/'.$controller,$params);
            ?>
        </div>
    <?php }else{
        echo $this->getContent();
    }?>

</div>